use_frameworks!

target 'SimpleWebViewController_Example' do
  pod 'SimpleWebViewController', :path => '../'

  target 'SimpleWebViewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
