osx_image: xcode7.3
language: objective-c

script:
- set -o pipefail && xcodebuild test -workspace Example/SimpleWebViewController.xcworkspace -scheme SimpleWebViewController-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
